In [4]:
#dataset used: Life expectancy

In [5]:
import pandas as pd
import matplotlib.pyplot as plt
life = pd.read_excel("Life_Expectancy.xlsx")
#type(life)
life.dropna()
life.head(10)

,Country,Year,Continent,Least Developed,Life Expectancy,Population,CO2 emissions,Health expenditure,Electric power consumption,Forest area,GDP per capita,Individuals using the Internet,Military expenditure,People practicing open defecation,People using at least basic drinking water services,Obesity among adults,Beer consumption per capita
0,Albania,2000,Europe,False,73.955,3089027,1.026213,7.233370,1414.703784,28.076642,3860.804627,0.114097,1.246360,0.888853,86.754471,12.8,1.33431
1,Albania,2001,Europe,False,74.288,3060173,1.055496,7.139524,1449.647413,28.123248,4299.546493,0.325798,1.309291,0.836397,86.904070,13.3,1.48995
2,Albania,2002,Europe,False,74.579,3051010,1.232379,6.909341,1351.230796,28.169854,4661.402695,0.390081,1.320034,0.781899,87.451635,13.9,1.28697
3,Albania,2003,Europe,False,74.828,3039616,1.338985,7.063490,1578.165919,28.216460,5000.049363,0.971900,1.336843,0.728191,87.987194,14.4,1.44830
4,Albania,2004,Europe,False,75.039,3026939,1.404059,6.773372,1469.264539,28.263066,5427.732662,2.420388,1.381158,0.675281,88.510583,15.0,1.37617
5,Albania,2005,Europe,False,75.228,3011487,1.338209,6.335542,1797.525487,28.309672,5865.301904,6.043891,1.350005,0.623198,89.021188,15.6,1.65180
6,Albania,2006,Europe,False,75.423,2992547,1.339996,6.009277,1722.072850,28.356277,6566.572828,9.609991,1.567769,0.571935,89.519132,16.2,1.79330
7,Albania,2007,Europe,False,75.646,2970017,1.393931,6.316834,1218.360146,28.402883,7283.342638,15.036115,1.820765,0.521500,90.004187,16.9,1.94369
8,Albania,2008,Europe,False,75.912,2947314,1.384311,5.139062,1213.124369,28.449489,8228.348041,23.860000,1.984869,0.471903,90.476151,17.5,2.12835
9,Albania,2009,Europe,False,76.221,2927519,1.441494,4.602225,1617.744156,28.496095,8813.029461,41.200000,1.517217,0.423170,90.934413,18.1,2.20543

In [6]:
life['Population'] = life['Population']/1000000
life.rename(columns = {'Population' : 'Population in millions'},inplace = True)
life.head(10)

,Country,Year,Continent,Least Developed,Life Expectancy,Population in millions,CO2 emissions,Health expenditure,Electric power consumption,Forest area,GDP per capita,Individuals using the Internet,Military expenditure,People practicing open defecation,People using at least basic drinking water services,Obesity among adults,Beer consumption per capita
0,Albania,2000,Europe,False,73.955,3.089027,1.026213,7.233370,1414.703784,28.076642,3860.804627,0.114097,1.246360,0.888853,86.754471,12.8,1.33431
1,Albania,2001,Europe,False,74.288,3.060173,1.055496,7.139524,1449.647413,28.123248,4299.546493,0.325798,1.309291,0.836397,86.904070,13.3,1.48995
2,Albania,2002,Europe,False,74.579,3.051010,1.232379,6.909341,1351.230796,28.169854,4661.402695,0.390081,1.320034,0.781899,87.451635,13.9,1.28697
3,Albania,2003,Europe,False,74.828,3.039616,1.338985,7.063490,1578.165919,28.216460,5000.049363,0.971900,1.336843,0.728191,87.987194,14.4,1.44830
4,Albania,2004,Europe,False,75.039,3.026939,1.404059,6.773372,1469.264539,28.263066,5427.732662,2.420388,1.381158,0.675281,88.510583,15.0,1.37617
5,Albania,2005,Europe,False,75.228,3.011487,1.338209,6.335542,1797.525487,28.309672,5865.301904,6.043891,1.350005,0.623198,89.021188,15.6,1.65180
6,Albania,2006,Europe,False,75.423,2.992547,1.339996,6.009277,1722.072850,28.356277,6566.572828,9.609991,1.567769,0.571935,89.519132,16.2,1.79330
7,Albania,2007,Europe,False,75.646,2.970017,1.393931,6.316834,1218.360146,28.402883,7283.342638,15.036115,1.820765,0.521500,90.004187,16.9,1.94369
8,Albania,2008,Europe,False,75.912,2.947314,1.384311,5.139062,1213.124369,28.449489,8228.348041,23.860000,1.984869,0.471903,90.476151,17.5,2.12835
9,Albania,2009,Europe,False,76.221,2.927519,1.441494,4.602225,1617.744156,28.496095,8813.029461,41.200000,1.517217,0.423170,90.934413,18.1,2.20543

In [7]:
life.describe()

,Year,Life Expectancy,Population in millions,CO2 emissions,Health expenditure,Electric power consumption,Forest area,GDP per capita,Individuals using the Internet,Military expenditure,People practicing open defecation,People using at least basic drinking water services,Obesity among adults,Beer consumption per capita
count,1904.000000,1904.000000,1904.000000,1904.000000,1904.000000,1904.000000,1904.000000,1904.000000,1904.000000,1904.000000,1904.000000,1904.000000,1904.000000,1904.000000
mean,2007.500000,70.817343,50.755832,5.356796,6.096855,3795.909462,30.547158,18094.113142,29.736220,2.206872,9.511306,86.836539,16.213393,2.199408
std,4.610983,8.489200,165.024724,6.218898,2.451488,4546.577231,20.855899,19389.828835,27.773360,2.969809,17.352796,17.603121,8.213384,1.903435
min,2000.000000,43.065000,0.333166,0.032419,0.410000,22.755823,0.000000,434.835252,0.000168,0.000000,0.000000,18.085445,1.100000,0.000000
25%,2003.750000,66.857250,4.218751,1.001108,4.214776,605.280403,11.630910,4614.709959,5.000000,1.087925,0.000000,82.268573,8.600000,0.484170
50%,2007.500000,73.009500,10.769182,3.545525,5.862418,2143.657892,30.888136,11155.012085,20.000000,1.532535,0.750000,94.881928,18.000000,1.791200
75%,2011.250000,76.765402,36.921236,7.629088,7.880948,5407.221626,46.671068,26366.811600,51.824997,2.414676,10.496432,99.500000,22.300000,3.720080
max,2015.000000,83.229268,1379.860000,50.954034,16.524073,25590.689430,91.978112,141634.703800,96.810326,32.655671,86.799174,100.000005,36.700000,7.877850

In [8]:
life.tail()

,Country,Year,Continent,Least Developed,Life Expectancy,Population in millions,CO2 emissions,Health expenditure,Electric power consumption,Forest area,GDP per capita,Individuals using the Internet,Military expenditure,People practicing open defecation,People using at least basic drinking water services,Obesity among adults,Beer consumption per capita
1899,Zimbabwe,2011,Africa,False,52.896,12.894323,0.884886,8.081738,606.643960,46.165723,2101.824051,8.400000,1.407162,26.876148,67.016076,10.8,2.05
1900,Zimbabwe,2012,Africa,False,55.032,13.115149,0.915735,6.918354,636.248991,46.046633,2375.927006,12.000000,1.859609,26.533231,66.491185,11.1,2.07
1901,Zimbabwe,2013,Africa,False,56.897,13.350378,0.919824,7.110148,608.761669,45.927543,2560.773267,15.500000,1.868420,26.188786,65.966474,11.3,2.12
1902,Zimbabwe,2014,Africa,False,58.410,13.586710,0.889104,8.133525,628.746242,45.808453,2612.455954,16.364740,1.888080,25.832157,65.454108,11.6,2.23
1903,Zimbabwe,2015,Africa,False,59.534,13.814642,0.899770,7.452066,609.124652,45.689363,2679.507615,22.742818,1.886876,25.463272,64.954929,11.9,1.93

In [9]:
countries = life.groupby('Country')
countries.get_group('Yemen')

,Country,Year,Continent,Least Developed,Life Expectancy,Population in millions,CO2 emissions,Health expenditure,Electric power consumption,Forest area,GDP per capita,Individuals using the Internet,Military expenditure,People practicing open defecation,People using at least basic drinking water services,Obesity among adults,Beer consumption per capita
1872,Yemen,2000,Asia,True,60.204,16.921157,0.830912,4.129000,133.857692,1.039832,2801.734275,0.056629,5.172722,33.754430,40.752000,7.4,0.07000
1873,Yemen,2001,Asia,True,60.683,17.409071,0.863343,4.666065,132.319557,1.039832,2957.067963,0.082500,4.915392,32.109504,40.879071,7.7,0.08000
1874,Yemen,2002,Asia,True,61.216,17.918369,0.896845,4.945151,142.741678,1.039832,3049.487731,0.090802,5.481015,31.912248,41.109331,8.0,0.06000
1875,Yemen,2003,Asia,True,61.781,18.443684,0.872385,4.832372,147.390647,1.039832,3127.208899,0.518796,6.895608,31.711958,41.343131,8.3,0.04000
1876,Yemen,2004,Asia,True,62.358,18.985001,0.984988,5.757578,155.283511,1.039832,3214.096446,0.604734,6.854552,30.377605,42.596501,8.6,0.05000
1877,Yemen,2005,Asia,True,62.931,19.540096,1.004601,5.514405,165.657089,1.039832,3334.008069,0.881223,5.301366,29.055013,43.769822,8.9,0.03377
1878,Yemen,2006,Asia,True,63.481,20.107416,1.049861,5.205854,173.387070,1.039832,3528.390136,1.048598,4.868317,27.745136,44.929215,9.2,0.03814
1879,Yemen,2007,Asia,True,63.997,20.687648,1.059569,5.529299,183.663580,1.039832,3647.328071,1.247824,4.308467,26.447198,46.075828,9.6,0.04518
1880,Yemen,2008,Asia,True,64.470,21.282514,1.093386,5.820770,193.883809,1.039832,3762.755487,5.010000,4.850723,25.161830,47.209122,10.0,0.03593
1881,Yemen,2009,Asia,True,64.892,21.892149,1.106333,5.761911,211.206251,1.039832,3864.116927,6.890000,4.445829,23.889314,48.328992,10.4,0.02845
1882,Yemen,2010,Asia,True,65.255,22.516464,1.180025,5.986204,230.128162,1.039832,3927.241241,9.960000,5.653648,22.629930,49.435323,10.8,0.06000
1883,Yemen,2011,Asia,True,65.549,23.154854,1.098258,5.159331,226.989460,1.039832,4162.544887,12.350000,4.685557,21.383955,50.528009,11.3,0.03000
1884,Yemen,2012,Asia,True,65.768,23.807586,0.963978,4.769531,254.849372,1.039832,3607.090566,14.905000,4.926462,20.151931,51.606598,11.8,0.04000
1885,Yemen,2013,Asia,True,65.920,24.473176,0.858491,5.195936,193.803773,1.039832,3491.204610,17.446500,4.573884,18.934096,52.671017,12.3,0.04000
1886,Yemen,2014,Asia,True,66.016,25.147112,1.106688,4.960832,193.804024,1.039832,3688.519409,20.000000,4.079527,17.730457,53.721523,12.9,0.03000
1887,Yemen,2015,Asia,True,66.066,25.823488,1.062211,4.841805,250.963212,1.039832,3697.704000,22.550000,3.966891,16.541733,54.757381,13.5,0.03000

In [10]:
life["Country"].unique()

array(['Albania', 'Algeria', 'Angola', 'Argentina', 'Armenia',
       'Australia', 'Austria', 'Bahrain', 'Bangladesh', 'Belarus',
       'Belgium', 'Benin', 'Bolivia', 'Botswana', 'Brazil',
       'Brunei Darussalam', 'Bulgaria', 'Cambodia', 'Cameroon', 'Canada',
       'Chile', 'China', 'Colombia', 'Congo Dem. Rep.', 'Congo Rep.',
       'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cyprus', 'Czechia',
       'Denmark', 'Ecuador', 'Egypt', 'El Salvador', 'Eritrea', 'Estonia',
       'Ethiopia', 'Finland', 'France', 'Gabon', 'Georgia', 'Germany',
       'Ghana', 'Greece', 'Guatemala', 'Honduras', 'Hungary', 'India',
       'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Jordan', 'Kazakhstan', 'Kenya', 'Kuwait',
       'Kyrgyz Republic', 'Latvia', 'Libya', 'Lithuania', 'Luxembourg',
       'Malaysia', 'Malta', 'Mauritius', 'Mexico', 'Moldova', 'Mongolia',
       'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia',
       'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Niger',
       'Nigeria', 'North Macedonia', 'Norway', 'Oman', 'Pakistan',
       'Panama', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal',
       'Qatar', 'Romania', 'Russian Federation', 'Saudi Arabia',
       'Senegal', 'Serbia', 'Slovak Republic', 'Slovenia', 'South Africa',
       'Spain', 'Sri Lanka', 'Sudan', 'Sweden', 'Switzerland',
       'Tajikistan', 'Tanzania', 'Thailand', 'Togo',
       'Trinidad and Tobago', 'Tunisia', 'Turkiye', 'Ukraine',
       'United Kingdom', 'United States', 'Uruguay', 'Venezuela', 'Yemen',
       'Zimbabwe'], dtype=object)

In [11]:
countries.count()

,Year,Continent,Least Developed,Life Expectancy,Population in millions,CO2 emissions,Health expenditure,Electric power consumption,Forest area,GDP per capita,Individuals using the Internet,Military expenditure,People practicing open defecation,People using at least basic drinking water services,Obesity among adults,Beer consumption per capita
Country,,,,,,,,,,,,,,,,
Albania,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16
Algeria,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16
Angola,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16
Argentina,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16
Armenia,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
United States,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16
Uruguay,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16
Venezuela,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16
Yemen,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16
Zimbabwe,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16

In [12]:
life.corr()

,Year,Least Developed,Life Expectancy,Population in millions,CO2 emissions,Health expenditure,Electric power consumption,Forest area,GDP per capita,Individuals using the Internet,Military expenditure,People practicing open defecation,People using at least basic drinking water services,Obesity among adults,Beer consumption per capita
Year,1.000000e+00,1.334857e-18,0.185849,0.016881,-0.007824,0.124885,0.031718,-0.009027,0.158618,0.472374,-0.014236,-0.094066,0.098240,0.235361,0.037643
Least Developed,1.334857e-18,1.000000e+00,-0.545006,-0.041313,-0.315040,-0.315096,-0.317721,0.079056,-0.321115,-0.374033,0.201352,0.628277,-0.761922,-0.568270,-0.312343
Life Expectancy,1.858493e-01,-5.450062e-01,1.000000,-0.034534,0.463116,0.470676,0.558860,-0.041576,0.575147,0.698531,-0.088004,-0.668292,0.823990,0.694936,0.424960
Population in millions,1.688149e-02,-4.131302e-02,-0.034534,1.000000,-0.052280,-0.095932,-0.081540,-0.046752,-0.102934,-0.081254,-0.005144,0.118525,-0.017643,-0.219247,-0.106689
CO2 emissions,-7.823612e-03,-3.150403e-01,0.463116,-0.052280,1.000000,0.093887,0.776558,-0.169936,0.857655,0.483592,0.052276,-0.394723,0.475386,0.551888,0.255271
Health expenditure,1.248848e-01,-3.150956e-01,0.470676,-0.095932,0.093887,1.000000,0.354718,-0.001508,0.212978,0.542416,-0.064171,-0.262417,0.393771,0.500943,0.492582
Electric power consumption,3.171809e-02,-3.177209e-01,0.558860,-0.081540,0.776558,0.354718,1.000000,-0.017010,0.801724,0.678180,-0.019666,-0.403023,0.502311,0.548934,0.356195
Forest area,-9.027123e-03,7.905573e-02,-0.041576,-0.046752,-0.169936,-0.001508,-0.017010,1.000000,-0.095339,0.059391,-0.242488,-0.041642,-0.034090,-0.187525,0.342658
GDP per capita,1.586180e-01,-3.211153e-01,0.575147,-0.102934,0.857655,0.212978,0.801724,-0.095339,1.000000,0.668715,0.004883,-0.402147,0.505428,0.556063,0.278368
Individuals using the Internet,4.723740e-01,-3.740327e-01,0.698531,-0.081254,0.483592,0.542416,0.678180,0.059391,0.668715,1.000000,-0.123056,-0.474456,0.582517,0.646108,0.550320
Military expenditure,-1.423614e-02,2.013525e-01,-0.088004,-0.005144,0.052276,-0.064171,-0.019666,-0.242488,0.004883,-0.123056,1.000000,0.275318,-0.149414,-0.039116,-0.211187
People practicing open defecation,-9.406615e-02,6.282767e-01,-0.668292,0.118525,-0.394723,-0.262417,-0.403023,-0.041642,-0.402147,-0.474456,0.275318,1.000000,-0.722295,-0.641666,-0.397542
People using at least basic drinking water services,9.824007e-02,-7.619222e-01,0.823990,-0.017643,0.475386,0.393771,0.502311,-0.034090,0.505428,0.582517,-0.149414,-0.722295,1.000000,0.724047,0.447996
Obesity among adults,2.353608e-01,-5.682700e-01,0.694936,-0.219247,0.551888,0.500943,0.548934,-0.187525,0.556063,0.646108,-0.039116,-0.641666,0.724047,1.000000,0.433195
Beer consumption per capita,3.764332e-02,-3.123430e-01,0.424960,-0.106689,0.255271,0.492582,0.356195,0.342658,0.278368,0.550320,-0.211187,-0.397542,0.447996,0.433195,1.000000